# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024 Robin Jarry
---
name: Check
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: ${{ github.actor != 'grout-bot' }}
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: l
      COVERAGE: true
      SANITIZE: address
      MESON_EXTRA_OPTS: --auto-features=enabled
    steps:
      - name: install system dependencies
        run: |
          set -xe
          sudo apt-get update -qy
          sudo apt-get install -qy --no-install-recommends \
            doxygen \
            gcc \
            gcovr \
            graphviz \
            libasan8 \
            libc-dev \
            libedit-dev \
            libreadline-dev \
            libyaml-dev \
            meson \
            ninja-build \
            pkg-config
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # force fetch all history
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - run: git config --global --add safe.directory $PWD
      - run: git rebase -x "git --no-pager log --oneline -1 && make tests" "HEAD~${{ github.event.pull_request.commits }}"
        if: ${{ github.event.pull_request.commits }}
      - run: make tests
        if: ${{ ! github.event.pull_request.commits }}
      - run: make coverage

  lint:
    if: ${{ github.actor != 'grout-bot' }}
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: dnf install -y gawk make clang-tools-extra git codespell
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # force fetch all history
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - run: git config --global --add safe.directory $PWD
      - run: git rebase -x "git --no-pager log --oneline -1 && make lint" "HEAD~${{ github.event.pull_request.commits }}"
        if: ${{ github.event.pull_request.commits }}
      - run: make lint
        if: ${{ ! github.event.pull_request.commits }}

  commits:
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.commits }}
    container: fedora:latest
    env:
      REVISION_RANGE: "HEAD~${{ github.event.pull_request.commits }}.."
    steps:
      - run: dnf install -y make git jq curl codespell
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # force fetch all history
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - run: git config --global --add safe.directory $PWD
      - run: make check-commits
